<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="GenWave.TestSupport" />
    <Using Include="GenWave.TestSupport.Fakes" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GenWave.Orchestration\GenWave.Orchestration.csproj" />
    <ProjectReference Include="..\GenWave.TestSupport\GenWave.TestSupport.csproj" />
  </ItemGroup>

</Project>
