namespace GenWave.Core.Domain;

/// <summary>
/// Where an ad spot's copy came from (SPEC F159.1; STORY-389; PLAN T398) — maps 1:1 to
/// <c>station.ad_source</c> by lowercase text, <see cref="AdSourceTokens"/> owning the mapping.
/// Governs two things downstream of this store: <c>Station:Ads:TargetCount</c> stock-keeping counts
/// <see cref="Llm"/>/<see cref="Pack"/> spots only (SPEC F159.3), and refresh
/// (<c>Station:Ads:RefreshDays</c>) exempts <see cref="Owner"/> spots outright.
/// </summary>
public enum AdSource
{
    /// <summary>Generated by <c>AdScriptWriter</c> (PLAN T400) from a sampled <c>ad_brief</c>.</summary>
    Llm,

    /// <summary>Typed by the station owner directly (PLAN T403's create-owner-draft) — never
    /// auto-refreshed (SPEC F159.3).</summary>
    Owner,

    /// <summary>Installed from an <c>ad-pack</c> catalog entry (PLAN T405) — <c>pack_slug</c> is
    /// always set for this source.</summary>
    Pack,
}
